In [1]:
import numpy as np

In [5]:
nums = [ 12,12, 13]
num_array = np.array(nums) # converts a list into an numpy ndarray
type(num_array)

numpy.ndarray

In [6]:
row1 =[1,2,3]
row2= [4,5,6]
row3 = [7,8,9]

In [8]:
row = np.array([row1,row2,row3])

In [9]:
row # returns 3X3 array (2d array)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
nums_arr =np.arange(5,11) # it creates a range of integer array from 5 inclusive and 11 not inclusive 5 to 10 
nums_arr

array([ 5,  6,  7,  8,  9, 10])

In [12]:
nums_arr =np.arange(5,11, 2) # 3rd argument for step size
nums_arr

array([5, 7, 9])

In [14]:
row.shape # row array has 3 ros and 3 coln

(3, 3)

In [15]:
row.size # returns number of elements in row

9

In [16]:
nums_arr.size

3

# one dim array indexing and slicing expressions
a[m]  = select element at index m, where m is an integer
a[-m] = Select the nth element from the end os the list, where n is an int.The last element in the list is adressed         as -1. the second to last element as -2, and so on.
a[m:n] = select elements with index starting at m and ending n-1
a[:] or a[0:-1] = select all the elements in the array
a[:n] = select element starting at 0 and going up n-1
a[m:] or a[m:-1] = selecting element starting at m and going up to end of the last element
a[m:n:p] = select elemnts with index m through n exclusive, with increment p
a[::-1] = select all the elements , in reverse order.


In [17]:
ones_array = np.ones(6)
ones_array

array([1., 1., 1., 1., 1., 1.])

In [19]:
zero = np.zeros(6)
zero

array([0., 0., 0., 0., 0., 0.])

In [21]:
one = np.ones((6,4))
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [108]:
# np.identity
x = np.identity(4)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [109]:
# np.eye. You can create identity matris using eye
x = np.eye(4)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [110]:
# you can use eye(0 function passing k value for offsetting the diagonal value)
x = np.eye(4, k =1)
x

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [111]:
x = np.eye(4, k =-1)
x

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [24]:
# uniform random numbers using random.rand() 
uniform = np.random.rand(4,5)
uniform

array([[0.86226039, 0.05401151, 0.19015562, 0.6578188 , 0.92877119],
       [0.32587919, 0.8399314 , 0.87375345, 0.33781403, 0.60376012],
       [0.24327502, 0.71281465, 0.48723268, 0.37817438, 0.76930185],
       [0.04042595, 0.81434758, 0.25523609, 0.32704087, 0.46201973]])

In [26]:
# normal distribution random numbers using random.randn()
normal = np.random.randn(4,5)
normal

array([[-1.0441994 ,  0.54776864,  1.29306056,  0.88677425, -0.38503378],
       [ 0.34861503,  1.58909323, -0.72143023, -1.65909982, -0.82320931],
       [ 0.48624304, -0.85086845,  0.46256849,  0.75390202, -0.42037158],
       [ 2.43398476, -0.50792009, -0.26711402, -0.65922699,  0.06831055]])

In [27]:
# random.randint() between range and 3rd argument is for number of elements from that range
integer = np .random.randint(10, 100, 3)
integer

array([21, 12, 18])

In [30]:
uniform = uniform.reshape(3,8)
uniform

array([[0.80439673, 0.19498695, 0.46544866, 0.97706912, 0.98477057,
        0.75454574, 0.47119757, 0.96257102],
       [0.59772721, 0.76105633, 0.14826267, 0.99452265, 0.27497219,
        0.57125895, 0.70620506, 0.77739734],
       [0.4416819 , 0.13442559, 0.41497293, 0.60534335, 0.97001057,
        0.84456286, 0.77011296, 0.41720235]])

In [76]:
dia = np.diag((6,3,8,10,11)) # it creates diagonal matrix for given elements
dia

array([[ 6,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0],
       [ 0,  0,  8,  0,  0],
       [ 0,  0,  0, 10,  0],
       [ 0,  0,  0,  0, 11]])

In [113]:
dai = np.diag(np.arange(0,20,5))
dai

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [81]:
#linspace - evenly spaced values between specified start and end value, using a  specified number of elements
d = np.linspace(1,9,18)
d


array([1.        , 1.47058824, 1.94117647, 2.41176471, 2.88235294,
       3.35294118, 3.82352941, 4.29411765, 4.76470588, 5.23529412,
       5.70588235, 6.17647059, 6.64705882, 7.11764706, 7.58823529,
       8.05882353, 8.52941176, 9.        ])

In [84]:
# fill with specified values in the array
x1 = np.full(10,5.4) 
x1

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [98]:
x2 = np.empty(9)  # cretae an empty arrray and fill it
x2.fill(7.0)
print(x2)

[7. 7. 7. 7. 7. 7. 7. 7. 7.]


In [28]:
#reshaping numpy arrays, when you reshape an array the elements of a reshaping array must be same as the one you for reshape.
uniform = np.random.rand(4,6)
uniform

array([[0.80439673, 0.19498695, 0.46544866, 0.97706912, 0.98477057,
        0.75454574],
       [0.47119757, 0.96257102, 0.59772721, 0.76105633, 0.14826267,
        0.99452265],
       [0.27497219, 0.57125895, 0.70620506, 0.77739734, 0.4416819 ,
        0.13442559],
       [0.41497293, 0.60534335, 0.97001057, 0.84456286, 0.77011296,
        0.41720235]])

In [36]:
# Array index and slicing
arr = np.arange(1,11)

In [38]:
arr[1]  # indexing same as python list 

2

In [39]:
row

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
print(row[1,1]) # using to extract mid element 

9


In [45]:
print(row[:,:2])

[[1 2]
 [4 5]
 [7 8]]


In [46]:
print(row[:2,:])

[[1 2 3]
 [4 5 6]]


In [48]:
# numpy for arithmatic operations
nums =[2,4,5,6,9]
np_sqr =np.sqrt(nums)
np_sqr

array([1.41421356, 2.        , 2.23606798, 2.44948974, 3.        ])

In [49]:
# natural log function or logerithms of base e
nums =[10,100,1000]
log_num = np.log(nums)
log_num

array([2.30258509, 4.60517019, 6.90775528])

In [226]:
logs_nums = np.log2(nums) #logerithms of base 2
logs_nums

array([1.        , 2.        , 2.32192809, 2.5849625 , 3.169925  ])

In [227]:
logs_nums = np.log10(nums) #logerithms of base 10
logs_nums

array([0.30103   , 0.60205999, 0.69897   , 0.77815125, 0.95424251])

In [99]:
# logerthemic seq np.logspace()
np.logspace(0,2,5) # logerthemic spaces between 10^0 to 10^2 (1 to 100) 5 elements

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [52]:
# exponenet of a number
nums =[2,4,5,6,9]
expo = np.exp(nums)
expo

array([7.38905610e+00, 5.45981500e+01, 1.48413159e+02, 4.03428793e+02,
       8.10308393e+03])

In [104]:
# meshgrid. when you give x, y lists like x =[-1, 0, 1] and y -[-2,0,2] and there are 9 points we can plot on th grap
# like (-1,-2), (-1,0),(-1,2) ... . So the meshgrid fuction retuns X array as 3X3 matrix and Y array s 3X3 matrix 
# using the x and y coordinates.
x = np.array([-1,0,1])
y = np.array([-2,0,2])
X, Y = np.meshgrid(x,y)
print(X)
print(Y)

[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
[[-2 -2 -2]
 [ 0  0  0]
 [ 2  2  2]]


In [105]:
# you can use the X and Y to do some more functions like below
z = (X + Y)**2
z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])

In [53]:
# can be used for sine, cosing functions usring np.sin(), np.cos()

# Matrix and Vector operations

In [55]:
# dot product of matrices ( also matrix multiplication number of col of a first matrix must match number row of second matrix)
A = np.random.randint(1,5,4)
B = np.random.randint(1,5,4)
print(A,B)
Z = np.dot(A,B)
Z

[4 4 3 4] [2 3 3 4]


45

In [59]:
# element wise matrix multiplication
C = np.random.randint(1,10,4)
print(C)
Z = np.array([A,B,C])
print(Z)
mult = np.multiply(Z,Z)
mult

[4 6 8 8]
[[4 4 3 4]
 [2 3 3 4]
 [4 6 8 8]]


array([[16, 16,  9, 16],
       [ 4,  9,  9, 16],
       [16, 36, 64, 64]])

In [60]:
# finding inverse of a matrix
A = [1,2,3]
B =[4,5,6]
c = [7,8,9]
d = np.array([A,B,c])

In [62]:
inve = np.linalg.inv(d) # inverse of an square matrix , it also independent matrix or non singular

In [63]:
inve

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [64]:
c= [8,10,12]
d =np.array([A,B,c])

In [65]:
inve = np.linalg.inv(d)  # it is a singular or dependent matrix so the inverse is not possible

LinAlgError: Singular matrix

In [66]:
# determinant of a matrix
deter = np.linalg.det(d) # returns 0 if the matrix is singular

In [67]:
deter

0.0

In [68]:
c = [7,8,9]
d = np.array([A,B,c])

In [69]:
deter = np.linalg.det(d)
deter

-9.51619735392994e-16

In [70]:
# Trace of a Matrix. Trace isa sum of all the values along the diagonal
tr = np.trace(d)
tr

15

In [211]:
# transpose of a matrix
a = np.ndarray((3,3))
print(a)
b = np.transpose(a)
b

[[30. 40. 50.]
 [31. 41. 51.]
 [32. 42. 52.]]


array([[30., 31., 32.],
       [40., 41., 42.],
       [50., 51., 52.]])

In [311]:
# np.inner()
c = np.array([[1,2,3],[4,5,6]])
np.inner(c,c)

array([[14, 32],
       [32, 77]])

In [312]:
np.outer(c,c)

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

In [314]:
np.kron([1,2,3],[1,2,3])

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

# Multidimentional Arrays

In [212]:
# horizontal stack of arrays a,b
np.hstack((a,b))


array([[30., 40., 50., 30., 31., 32.],
       [31., 41., 51., 40., 41., 42.],
       [32., 42., 52., 50., 51., 52.]])

In [213]:
np.vstack((a,b)) # vertical stack of arrays a,b

array([[30., 40., 50.],
       [31., 41., 51.],
       [32., 42., 52.],
       [30., 31., 32.],
       [40., 41., 42.],
       [50., 51., 52.]])

In [214]:
# arithmatic  operations are element wise and the shape should be same for both arrays
a+b

array([[ 60.,  71.,  82.],
       [ 71.,  82.,  93.],
       [ 82.,  93., 104.]])

In [215]:
a-b

array([[  0.,   9.,  18.],
       [ -9.,   0.,   9.],
       [-18.,  -9.,   0.]])

In [216]:
a*b

array([[ 900., 1240., 1600.],
       [1240., 1681., 2142.],
       [1600., 2142., 2704.]])

In [217]:
a/b

array([[1.        , 1.29032258, 1.5625    ],
       [0.775     , 1.        , 1.21428571],
       [0.64      , 0.82352941, 1.        ]])

In [218]:
a*2

array([[ 60.,  80., 100.],
       [ 62.,  82., 102.],
       [ 64.,  84., 104.]])

In [223]:
# concatinate function
z = np.concatenate([a,b]) 
z

array([[30., 40., 50.],
       [31., 41., 51.],
       [32., 42., 52.],
       [30., 31., 32.],
       [40., 41., 42.],
       [50., 51., 52.]])

In [224]:
z = np.concatenate([a,b],axis =1)  # defualt axis =0 which is y axis(vertical)
z 

array([[30., 40., 50., 30., 31., 32.],
       [31., 41., 51., 40., 41., 42.],
       [32., 42., 52., 50., 51., 52.]])

In [145]:
# np.fromfunction(func,(3,3), dtype=int). fromfunction taks function as first argument and shape as second argument 
# shape for 3,3 is [[0,1,2],[0,1,2],[0,1,2]] and it runs the function with each element
func = lambda m, n: n+10*m
a = np.fromfunction(func,(6,6))
a

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [10., 11., 12., 13., 14., 15.],
       [20., 21., 22., 23., 24., 25.],
       [30., 31., 32., 33., 34., 35.],
       [40., 41., 42., 43., 44., 45.],
       [50., 51., 52., 53., 54., 55.]])

### nd indexing and slicing

In [146]:
a[:, :] # slicing 2 dim array takes  maximum 2 arguments . first is for the row and second one is for column
a[1]

array([10., 11., 12., 13., 14., 15.])

In [147]:
a[:, 1] # the second column

array([ 1., 11., 21., 31., 41., 51.])

In [148]:
a[1,:] # second row

array([10., 11., 12., 13., 14., 15.])

In [149]:
a[:3,:3] # upper half disg block matrix

array([[ 0.,  1.,  2.],
       [10., 11., 12.],
       [20., 21., 22.]])

In [150]:
a[3:,3:] # lower right off-diagonal block matrix

array([[33., 34., 35.],
       [43., 44., 45.],
       [53., 54., 55.]])

In [151]:
a[:3,3:] # upper right half

array([[ 3.,  4.,  5.],
       [13., 14., 15.],
       [23., 24., 25.]])

In [152]:
a[3:,:3] # lower left

array([[30., 31., 32.],
       [40., 41., 42.],
       [50., 51., 52.]])

In [153]:
a[::2,::2] # every second element starting from 0,0

array([[ 0.,  2.,  4.],
       [20., 22., 24.],
       [40., 42., 44.]])

In [154]:
a[1::2,1::3] # every second row and the thrid elemnet (column) slected

array([[11., 14.],
       [31., 34.],
       [51., 54.]])

In [155]:
# Views 
b = a[1:5,1:5]
c = a[1:5,1:5].copy()
b

array([[11., 12., 13., 14.],
       [21., 22., 23., 24.],
       [31., 32., 33., 34.],
       [41., 42., 43., 44.]])

In [157]:
# array slicing operations are alternative views of the same underlying arraydata. if you change the view then the 
# original array will also be updated
b[:,:] = 0
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [158]:
a

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [10.,  0.,  0.,  0.,  0., 15.],
       [20.,  0.,  0.,  0.,  0., 25.],
       [30.,  0.,  0.,  0.,  0., 35.],
       [40.,  0.,  0.,  0.,  0., 45.],
       [50., 51., 52., 53., 54., 55.]])

In [159]:
# you an use copy function to extract the elements permanantly without affecting initial array
c

array([[11., 12., 13., 14.],
       [21., 22., 23., 24.],
       [31., 32., 33., 34.],
       [41., 42., 43., 44.]])

In [160]:
a[1:5,1:5] = c[:,:]
a

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [10., 11., 12., 13., 14., 15.],
       [20., 21., 22., 23., 24., 25.],
       [30., 31., 32., 33., 34., 35.],
       [40., 41., 42., 43., 44., 45.],
       [50., 51., 52., 53., 54., 55.]])

In [161]:
#checking values in the array 
a> 5 # return true if the element is greater than 5 else false and returns as an array

array([[False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [162]:
a[a>5] # returns all the values that are greater than 5

array([10., 11., 12., 13., 14., 15., 20., 21., 22., 23., 24., 25., 30.,
       31., 32., 33., 34., 35., 40., 41., 42., 43., 44., 45., 50., 51.,
       52., 53., 54., 55.])

In [163]:
#np.ndarray.flatten(). Creates a copy of an N-dimentional array, and reinterprets it as a one -dim array
b = np.ndarray.flatten(a)
b
# altering b doesn't affect a

array([ 0.,  1.,  2.,  3.,  4.,  5., 10., 11., 12., 13., 14., 15., 20.,
       21., 22., 23., 24., 25., 30., 31., 32., 33., 34., 35., 40., 41.,
       42., 43., 44., 45., 50., 51., 52., 53., 54., 55.])

In [172]:
c = a.ravel() # does same thing as flatten function but alters a 
c[1] =100
print(c)
a

[  0. 100.   2.   3.   4.   5.  10.  11.  12.  13.  14.  15.  20.  21.
  22.  23.  24.  25.  30.  31.  32.  33.  34.  35.  40.  41.  42.  43.
  44.  45.  50.  51.  52.  53.  54.  55.]


array([[  0., 100.,   2.,   3.,   4.,   5.],
       [ 10.,  11.,  12.,  13.,  14.,  15.],
       [ 20.,  21.,  22.,  23.,  24.,  25.],
       [ 30.,  31.,  32.,  33.,  34.,  35.],
       [ 40.,  41.,  42.,  43.,  44.,  45.],
       [ 50.,  51.,  52.,  53.,  54.,  55.]])

In [177]:
c = np.ndarray.ravel(a) # this will alter a 
c[1 ]=100
a

array([[  0., 100.,   2.,   3.,   4.,   5.],
       [ 10.,  11.,  12.,  13.,  14.,  15.],
       [ 20.,  21.,  22.,  23.,  24.,  25.],
       [ 30.,  31.,  32.,  33.,  34.,  35.],
       [ 40.,  41.,  42.,  43.,  44.,  45.],
       [ 50.,  51.,  52.,  53.,  54.,  55.]])

In [185]:
#np.squeeze. removes axes with length 1
b = np.array([[[1,2,2],[1,2,3],[1,2,3]]])
c = np.squeeze(b)
print(b.shape)
print(c.shape)
c

(1, 3, 3)
(3, 3)


array([[1, 2, 2],
       [1, 2, 3],
       [1, 2, 3]])

# Aggregate Functions

In [229]:
arr = np.random.randint(100, 200, 10)
arr

array([102, 135, 108, 196, 101, 158, 199, 180, 116, 193])

In [231]:
arr.mean() # the average of all values in the array

148.8

In [232]:
arr.std() # the standard deviation 

38.94303532083754

In [234]:
arr.var() #variance

1516.56

In [236]:
arr.sum() # sum of all values in the arr

1488

In [237]:
arr.prod() #prodcut of all elements

3966198900613434368

In [238]:
arr.cumsum() # cumulative sum of all element

array([ 102,  237,  345,  541,  642,  800,  999, 1179, 1295, 1488])

In [239]:
arr.cumprod() # cumulative product of all element

array([                102,               13770,             1487160,
                 291483360,         29439819360,       4651491458880,
           925646800317120,  166616424057081600,  880761116911913984,
       3966198900613434368])

In [240]:
arr.min() # min value

101

In [241]:
arr.max() # max value

199

In [242]:
arr.all() # returns true if all elements are not equal to zero

True

In [245]:
arr[0] = 0
arr.all()

False

In [247]:
arr.any(0)

True

In [252]:
# logical AND operation using np
a = np.array([1,2,3])
b = np.array([0,1,1])
np.logical_and(a,b)

array([False,  True,  True])

In [253]:
np.logical_or(a,b) # logocal OR

array([ True,  True,  True])

In [254]:
np.logical_not(a) # logical not

array([False, False, False])

In [255]:
np.logical_xor(a,b) # logiccal xor

array([ True, False, False])

In [261]:
c = np.linspace(-4,4,9)
c

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [266]:
np.where(c>0, c**2, c**3) # where function , condition c> 0 : When True, yield x(c**2), otherwise yield y(c**3).

array([-64., -27.,  -8.,  -1.,   0.,   1.,   4.,   9.,  16.])

In [268]:
# np.select funtion works similarly as where()
np.select([c<-1,c<2,c>=2],[c**2,c**3,c**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [271]:
np.choose([0,0,0,1,1,1,2,2,2], [c**2,c**3,c**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

# set Operations

In [273]:
a = np.unique([1,2,3,3,7])
a # returns unique value of an array

array([1, 2, 3, 7])

In [274]:
b =np.unique([2,3,4,4,5,6,5])
np.in1d(a,b) # checks existance of elements in another array, argument order matters

array([False,  True,  True, False])

In [275]:
np.in1d(b,a)

array([ True,  True, False, False, False])

In [280]:
np.intersect1d(a,b) # intersection of arrays

array([2, 3])

In [281]:
np.setdiff1d(a,b)# elements contained in a but not in b

array([1, 7])

In [283]:
np.union1d(a,b) # union of a and b

array([1, 2, 3, 4, 5, 6, 7])

In [286]:
np.flipud(arr) # flips upside down (reversed)

array([193, 116, 180, 199, 158, 101, 196, 108, 135,   0])

In [292]:
arr =np.array([[1,2,3],[4,5,6],[7,8,9]]) # flips left to right
np.fliplr(arr)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [293]:
np.rot90(arr) # rotates 90 degree angle

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

In [304]:
arr = np.fliplr(arr)
print(arr)
np.sort(arr) # sorts the array by row wise as axis =1 by defualt


[[3 2 1]
 [6 5 4]
 [9 8 7]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [305]:
arr = np.fliplr(arr)
arr[1,1] =10
print(arr)

np.sort(arr, axis=0) # sorts by column

[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]


array([[ 1,  2,  3],
       [ 4,  8,  6],
       [ 7, 10,  9]])